---
version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    cooldown:
      semver-major-days: 30
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    cooldown:
      semver-major-days: 30
    schedule:
      interval: "weekly"
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "/"
    cooldown:
      semver-major-days: 30
    schedule:
      interval: "weekly"
    groups:
      docker-compose-images:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      semver-major-days: 30
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
