[tool.poetry]
name = "discord-blue"
version = "0.1.0"
description = ""
authors = ["Chris Busillo <info@shinycomputers.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
toml = "^0.10.2"
discord = "^2.3.2"
printnodeapi = "^0.2.0"
pynacl = "^1.5.0"


[tool.poetry.group.dev.dependencies]
setuptools = "^68.2.2"

[tool.poetry.scripts]
main = 'discord_blue.main:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

