[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "discord-blue"
version = "0.1.0"
description = ""
authors = [{ name = "Chris Busillo", email = "info@shinycomputers.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "toml>=0.10.2",
    "nextcord>=2.5.1",
    "pynacl>=1.5.0",
]

[project.optional-dependencies]
dev = [
    "setuptools>=68.2.2",
    "black>=23.9.1",
    "types-toml>=0.10.8.7",
]

[project.scripts]
discord-blue = "discord_blue.__main__:main"

[tool.mypy]
strict = true
python_version = 3.14
warn_any_return = false
warn_no_untyped_call = false
