[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "discord-blue"
version = "0.2.0"
description = ""
authors = [{ name = "Chris Busillo", email = "info@shinycomputers.com" }]
readme = "README.md"

requires-python = ">=3.13"
dependencies = [
    "toml>=0.10.2",
    "nextcord>=2.5.1",
    "torch>=2.7.0"
]
[dependency-groups]
dev = [
    "setuptools>=68.2.2",
    "black>=23.9.1",
    "types-toml>=0.10.8.7",
    "mypy>=1.4.2",
]
[project.scripts]
discord-blue = "discord_blue.__main__:main"

[tool.mypy]
strict = true
python_version = 3.13
