name: Deploy to Production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: master
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          ping -c 1 $PRODUCTION_SERVER
          ssh-keyscan -H $PRODUCTION_SERVER >> ~/.ssh/known_hosts
        shell: bash

      - name: Clone & Install
        run: |
          ssh $PRODUCTION_USER@$PRODUCTION_SERVER "cd /opt/discord-blue; \
          export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring; \
          git pull; \ 
          poetry lock -n; \
          poetry install; \
          systemctl restart discord-blue"
        shell: bash
